# Generated by Django 3.0.8 on 2020-07-16 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamageEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HealEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healing', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(max_length=20)),
                ('increasing', models.BooleanField()),
                ('strength', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('special', 'special'), ('physical', 'physical'), ('status', 'status')], max_length=20, null=True)),
                ('precision', models.IntegerField()),
                ('power_point', models.IntegerField()),
                ('capacity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.PokemonType')),
                ('damage_effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon.DamageEffect')),
                ('heal_effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon.HealEffect')),
                ('stat_effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon.StatEffect')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture_url', models.CharField(blank=True, max_length=500, null=True)),
                ('attack', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('capacity1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacity_1', to='pokemon.PokemonCapacity')),
                ('capacity2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacity_2', to='pokemon.PokemonCapacity')),
                ('capacity3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacity_3', to='pokemon.PokemonCapacity')),
                ('capacity4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacity_4', to='pokemon.PokemonCapacity')),
                ('type_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_1', to='pokemon.PokemonType')),
                ('type_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_2', to='pokemon.PokemonType')),
            ],
        ),
    ]
